kind: template
load: nx-devops-latest.yaml

data:
  workspace:
    appsPath: projects
  cache:
    enabled: false
  image:
    tag: latest
  setup:
    enabled: true
  build:
    enabled: true
  lint:
    enabled: true
  test:
    enabled: true
    before:
      enabled: true
      commands:
        - rm -rf ./node_modules/sharp
        - npm --arch=x64 --platform=linux i sharp
  version:
    enabled: true
  e2e:
    enabled: true
    before:
      enabled: true
      commands:
        - rm -rf ./node_modules/sharp
        - npm --arch=x64 --platform=linux i sharp
        - rm -rf ./node_modules/mongodb-memory-server
        - npm i mongodb-memory-server
  docker:
    enabled: true
  npm:
    publish:
      enabled: false
  helm:
    deploy:
      enabled: true
    lint:
      enabled: true
    publish:
      enabled: true
  kubeval:
    enabled: false
  drone:
    enabled: false
