kind: template
load: nx-devops-latest-dev.yaml

data:
  workspace:
    appsPath: projects
  image:
    tag: latest
  setup:
    enabled: true
  build:
    enabled: false
  lint:
    enabled: false
  test:
    enabled: false
  version:
    enabled: false
  e2e:
    enabled: false
  docker:
    enabled: false
  npm:
    publish:
      enabled: false
  helm:
    deploy:
      enabled: true
    lint:
      enabled: false
    publish:
      enabled: false
  kubeval:
    enabled: false
  drone:
    enabled: false
