image:
  # -- image tag
  tag: 'latest-dev'
  # -- image pull policy
  pullPolicy: Always

ingressroute:
  routes:
    - host: development-api.outworld.fr
      priority: 10
      services:
        - passHostHeader: true
          name: api-otwld-fr-ecosystem-api-otwld-fr
          port: 80
    - host: development-db.outworld.fr
      priority: 10
      services:
        - passHostHeader: true
          name: db-otwld-fr-ecosystem-db-otwld-fr
          port: 27017
backup:
  enabled: false
mongodb:
  auth:
    usernames:
      - dev
env:
  NODE_ENV: development

  MONGODB_PORT: 27017
  MONGODB_USERNAME: dev
  MONGODB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: development-secret
        key: mongodb-passwords
  S3_PULIC_KEY:
    valueFrom:
      secretKeyRef:
        name: ecosystem-secret
        key: s3-public-key
  S3_PRIVATE_KEY:
    valueFrom:
      secretKeyRef:
        name: ecosystem-secret
        key: s3-private-key


persistence:
  media:
    enabled: false
    size: 512Mi
