image:
  # -- image tag
  tag: 'latest-dev'
  # -- image pull policy
  pullPolicy: Always

ingressroute:
  routes:
    - host: development-api.outworld.fr
      priority: 10
      services:
        - passHostHeader: true
          name: api-otwld-fr-ecosystem-api-otwld-fr
          port: 80

backup:
  enabled: false
mongodb:
  auth:
    usernames:
      - dev
env:
  NODE_ENV: development

  MONGODB_PORT: 27017
  MONGODB_USERNAME: dev
  MONGODB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: development-secret
        key: mongodb-passwords

persistence:
  media:
    enabled: false
    size: 512Mi
