image:
  # -- image tag
  tag: 'latest'
  # -- image pull policy
  pullPolicy: Always

ingressroute:
  routes:
    - host: api.outworld.fr
      priority: 10
      services:
        - passHostHeader: true
          name: api-otwld-fr-ecosystem-api-otwld-fr
          port: 80

backup:
  enabled: false
mongodb:
  auth:
    usernames:
      - production
env:
  NODE_ENV: production
  GRAPHQL_PLAYGROUND: false
  MONGODB_PORT: 27017
  MONGODB_USERNAME: production
  MONGODB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: ecosystem-secret
        key: mongodb-passwords
  S3_PULIC_KEY:
    valueFrom:
      secretKeyRef:
        name: ecosystem-secret
        key: s3-public-key
  S3_PRIVATE_KEY:
    valueFrom:
      secretKeyRef:
        name: ecosystem-secret
        key: s3-private-key
  LOG_API_DEBUG: false
  LOG_GRAPHQL_DEBUG: false

persistence:
  media:
    enabled: false
    size: 512Mi
