export const defaultDaisyUIConfig = {
  styled: true,
  base: true,
  utils: true,
  logs: true,
  rtl: false,
  prefix: "",
  darkTheme: "dark",
  themes: [
    'light',
    'corporate',
    'dark',
    'forest',
    'aqua',
    'luxury',
    'synthwave',
    'retro',
    'cyberpunk',
    'valentine',
    {
      default: {
        primary: '#104cba',
        'primary-content': '#ffffff',
        secondary: '#222f5a',
        accent: '#104cba',
        neutral: '#222f5a',
        'neutral-content': '#ffffff',
        'base-100': '#FFFFFF',
        'base-200': '#e5eef6',
        info: '#0095ff',
        'info-focus': '#42aaff',
        success: '#00d68f',
        warning: '#ffaa00',
        error: '#ff3d71',
      },
    },
  ],
};
