export type Skill =
  | 'Angular'
  | 'RxJS'
  | 'Typescript'
  | 'IndexedDB'
  | 'Material'
  | 'Webpack'
  | 'GraphQL'
  | 'PostgreSQL'
  | 'SCSS'
  | 'TDD'
  | 'Kubernetes'
  | 'Docker'
  | 'DevOps'
  | 'Gitlab'
  | 'Sonarqube'
  | 'Jest'
  | 'Cypress'
  | 'Sentry'
  | "Pilotage d'une equipe technique"
  | 'Suivi d’avancement et planning'
  | 'Animation et conduite de réunion'
  | 'Automatisation de processus métier et monitoring de workflow'
  | 'Méthodologie Agile'
  | 'Architecture de fonctionnalités complexes'
  | string;
